module.exports.story = {
  global: {
    description: "",
    name: "",
    category: "",
    public: "",
  },
  scenes: [
    {
      textbox: {
        "a04384ef-250e-4cae-93cf-46e90bf97986": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 38.99,
            top: 32.97,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "a04384ef-250e-4cae-93cf-46e90bf97986",
        },
        "24f2587a-ba9f-4435-9122-900f6fd2f21c": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 727.89,
            top: 437.59,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Helvetica, sans-serif",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "24f2587a-ba9f-4435-9122-900f6fd2f21c",
        },
      },
      image: {
        "5ec5270a-8e09-4256-8525-24a4ef48504a": {
          obj: {
            type: "image",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 506.93,
            top: 248.77,
            width: 900,
            height: 502,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 0,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 0.21,
            scaleY: 0.21,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            cropX: 0,
            cropY: 0,
            src: "http://localhost:4242/uploads/127734-middle_1695066532548.png",
            crossOrigin: null,
            filters: [],
          },
          Actions: [],
          id: "5ec5270a-8e09-4256-8525-24a4ef48504a",
        },
      },
      rect: {
        "926d2f27-a936-425a-921e-16a88fe870b9": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 36.37,
            top: 413.07,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 0.49,
            scaleY: 0.49,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [
            {
              type: "add",
              target: "",
              number: "",
            },
            {
              type: "subs",
              target: "",
              number: "",
            },
            {
              type: "shop",
              target: "",
              number: "",
            },
            {
              type: "subs",
              target: "",
              number: "",
            },
          ],
          id: "926d2f27-a936-425a-921e-16a88fe870b9",
        },
      },
      background:
        "http://localhost:4242/uploads/47cd031e07098e31e857a8aa439e63c2_1693425923677_1695129340740.jpeg",
    },
    {
      textbox: {
        "a04384ef-250e-4cae-93cf-46e90bf97986": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 53.99,
            top: 36.97,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "a04384ef-250e-4cae-93cf-46e90bf97986",
        },
        "24f2587a-ba9f-4435-9122-900f6fd2f21c": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 396.94,
            top: 83.92,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "24f2587a-ba9f-4435-9122-900f6fd2f21c",
        },
      },
      background: null,
    },
  ],
}
