module.exports.story = {
  global: {
    description: "",
    name: "",
    category: "",
    public: "",
  },
  scenes: [
    {
      rect: {
        "aefe7b7b-5d3f-4d52-ac15-933f565f2910": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 466.84,
            top: 121.87,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [],
          id: "aefe7b7b-5d3f-4d52-ac15-933f565f2910",
          link: "",
          pos: {
            percX: 51.987058103127524,
            percY: 24.12711057869924,
          },
        },
      },
      textbox: {
        "901a13ff-a88a-465c-8dfa-49c93ebe4a84": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 51.98,
            top: 32.96,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "901a13ff-a88a-465c-8dfa-49c93ebe4a84",
          link: "",
          pos: {
            percX: 5.788418708240535,
            percY: 6.525117545162089,
          },
        },
        "f9a61de0-6849-49c5-b888-6b0069069375": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 542.83,
            top: 204.78,
            width: 200,
            height: 45.2,
            fill: "#cd3535",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 0.43,
            scaleY: 0.43,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "f9a61de0-6849-49c5-b888-6b0069069375",
          link: "",
          pos: {
            percX: 60.448325232645615,
            percY: 40.54024561624864,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "901a13ff-a88a-465c-8dfa-49c93ebe4a84": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 51.98,
            top: 32.96,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "901a13ff-a88a-465c-8dfa-49c93ebe4a84",
          link: "",
          pos: {
            percX: 5.788803091790811,
            percY: 6.525876364396651,
          },
        },
      },
      rect: {
        "aefe7b7b-5d3f-4d52-ac15-933f565f2910": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 211.93,
            top: 140.85,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [],
          id: "aefe7b7b-5d3f-4d52-ac15-933f565f2910",
          link: "",
          pos: {
            percX: 23.600504912685604,
            percY: 27.883289920603875,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "901a13ff-a88a-465c-8dfa-49c93ebe4a84": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 51.98,
            top: 32.96,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "901a13ff-a88a-465c-8dfa-49c93ebe4a84",
          link: "",
          pos: {
            percX: 5.788803091790811,
            percY: 6.525876364396651,
          },
        },
      },
      rect: {
        "aefe7b7b-5d3f-4d52-ac15-933f565f2910": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 211.93,
            top: 140.85,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [],
          id: "aefe7b7b-5d3f-4d52-ac15-933f565f2910",
          link: "",
          pos: {
            percX: 23.600504912685604,
            percY: 27.883289920603875,
          },
        },
      },
      background: null,
    },
  ],
  heroes: [],
  weapons: [],
  consumables: [],
}
