module.exports.story = {
  global: {
    description: "",
    name: "",
    category: "",
    public: "",
  },
  scenes: [
    {
      textbox: {
        "997ea2d3-1966-4324-8d18-f6a5b6c6b3c5": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 60.98,
            top: 117.95,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "997ea2d3-1966-4324-8d18-f6a5b6c6b3c5",
          link: "1",
          pos: {
            percX: 5.914645974781765,
            percY: 20.33839853432482,
          },
        },
        "ffa46fc0-6670-49d0-a7ff-64d4ed67f345": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 457.87,
            top: 174.07,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [
            {
              type: "subs",
              target: "",
              number: "",
            },
          ],
          id: "ffa46fc0-6670-49d0-a7ff-64d4ed67f345",
          link: "1",
          pos: {
            percX: 44.41028128031038,
            percY: 30.014763446875254,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "500d4eed-bb07-4001-9cc4-8aa81d70b698": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 1,
            top: 18.56,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [
            {
              type: "add",
              target: "life",
              number: "",
            },
          ],
          id: "500d4eed-bb07-4001-9cc4-8aa81d70b698",
          link: "",
          pos: {
            percX: 0.09416195856873823,
            percY: 3.107758342934927,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "500d4eed-bb07-4001-9cc4-8aa81d70b698": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 1,
            top: 18.56,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [
            {
              type: "add",
              target: "life",
              number: "",
            },
          ],
          id: "500d4eed-bb07-4001-9cc4-8aa81d70b698",
          link: "",
          pos: {
            percX: 0.09416195856873823,
            percY: 3.107758342934927,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "500d4eed-bb07-4001-9cc4-8aa81d70b698": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 1,
            top: 18.56,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [
            {
              type: "add",
              target: "life",
              number: "",
            },
          ],
          id: "500d4eed-bb07-4001-9cc4-8aa81d70b698",
          link: "",
          pos: {
            percX: 0.09416195856873823,
            percY: 3.107758342934927,
          },
        },
      },
      background: null,
    },
  ],
  heroes: [
    {
      class: "barbarian",
      img: null,
      name: "Michel",
      heal: 4,
      maxHeal: 4,
      money: 100,
      unit: "",
      equipped: {
        weapons: [],
      },
      inventory: {
        weapons: [],
        items: [],
      },
      skills: {
        agility: "20",
        strength: "20",
        intelligence: "20",
        resistance: "20",
      },
    },
    {
      class: "barbarian",
      img: null,
      name: "Tuj",
      heal: 4,
      maxHeal: 4,
      money: 100,
      unit: "",
      equipped: {
        weapons: [],
      },
      inventory: {
        weapons: [],
        items: [],
      },
      skills: {
        agility: "10",
        strength: "10",
        intelligence: "10",
        resistance: "50",
      },
    },
    {
      class: "barbarian",
      img: "account_1695285567128_1695298967812.png",
      name: "Tuj",
      heal: 4,
      maxHeal: 4,
      money: 100,
      unit: "",
      equipped: {
        weapons: [],
      },
      inventory: {
        weapons: [],
        items: [],
      },
      skills: {
        agility: "10",
        strength: "10",
        intelligence: "10",
        resistance: "50",
      },
    },
  ],
  weapons: [],
  consumables: [],
}
