module.exports.story = {
  global: {
    description: "",
    name: "",
    category: "",
    public: "",
  },
  scenes: [
    {
      textbox: {
        "9427e66d-02d3-457e-a211-baf081b8d817": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 540.93,
            top: 87.92,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "scene 1",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "9427e66d-02d3-457e-a211-baf081b8d817",
          link: "",
          pos: {
            percX: 52.46653734238603,
            percY: 15.160254337751914,
          },
        },
      },
      rect: {
        "d44bf41c-d02f-4964-973b-1a210c475ddf": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 534.93,
            top: 183.84,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: "#FFFFFF",
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [
            {
              type: "add",
              target: "life",
              number: "2",
            },
          ],
          id: "d44bf41c-d02f-4964-973b-1a210c475ddf",
          link: "1",
          pos: {
            percX: 51.88457807953443,
            percY: 31.69996766892984,
          },
        },
      },
      background:
        "http://localhost:4242/uploads/47cd031e07098e31e857a8aa439e63c2_1693425923677_1695129340740_1695332122464.jpeg",
    },
    {
      textbox: {
        "e3bc25f0-5f53-42b7-beab-faae349dce8e": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 258.96,
            top: 149.87,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "scene 2",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "e3bc25f0-5f53-42b7-beab-faae349dce8e",
          link: "",
          pos: {
            percX: 25.11736178467507,
            percY: 25.842439918094623,
          },
        },
      },
      rect: {
        "6abd995c-2871-4065-9dde-5ec926b1c9d9": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 614.91,
            top: 300.74,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [
            {
              type: "subs",
              target: "life",
              number: "1",
            },
          ],
          id: "6abd995c-2871-4065-9dde-5ec926b1c9d9",
          link: "2",
          pos: {
            percX: 59.64209505334627,
            percY: 51.8573122103675,
          },
        },
      },
      background:
        "http://localhost:4242/uploads/47cd031e07098e31e857a8aa439e63c2_1693425923677_1695129340740_1695332122464.jpeg",
    },
    {
      textbox: {
        "64c1b72b-1113-4864-bba1-b58315f3dc46": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 183.97,
            top: 154.86,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "scene 3",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "64c1b72b-1113-4864-bba1-b58315f3dc46",
          link: "",
          pos: {
            percX: 17.84384093113482,
            percY: 26.7028774652441,
          },
        },
      },
      rect: {
        "68fecc7a-2859-4866-a658-04ad2fef83bf": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 565.92,
            top: 278.76,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [],
          id: "68fecc7a-2859-4866-a658-04ad2fef83bf",
          link: "3",
          pos: {
            percX: 54.89039767216295,
            percY: 48.067248625929516,
          },
        },
      },
      background:
        "http://localhost:4242/uploads/47cd031e07098e31e857a8aa439e63c2_1693425923677_1695129340740_1695332122464.jpeg",
    },
    {
      textbox: {
        "69e9ed0c-9884-4755-b975-b4c3f79bd6b0": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 137.98,
            top: 160.86,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "scene 4",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "69e9ed0c-9884-4755-b975-b4c3f79bd6b0",
          link: "",
          pos: {
            percX: 13.383123181377302,
            percY: 27.737471710313617,
          },
        },
      },
      rect: {
        "422fff09-3af1-4d99-8d26-7713dc740eb2": {
          obj: {
            type: "rect",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 505.93,
            top: 230.8,
            width: 200,
            height: 200,
            fill: "grey",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            rx: 0,
            ry: 0,
          },
          Actions: [],
          id: "422fff09-3af1-4d99-8d26-7713dc740eb2",
          link: "0",
          pos: {
            percX: 49.071774975751694,
            percY: 39.797391960340555,
          },
        },
      },
      background:
        "http://localhost:4242/uploads/47cd031e07098e31e857a8aa439e63c2_1693425923677_1695129340740_1695332122464.jpeg",
    },
  ],
  heroes: [
    {
      class: "fze",
      img: null,
      name: "zeg",
      heal: 4,
      maxHeal: 4,
      money: 100,
      unit: "",
      equipped: {
        weapons: [],
      },
      inventory: {
        weapons: [],
        items: [],
      },
      skills: {
        agility: 0,
        strength: 0,
        intelligence: 0,
        resistance: 0,
      },
    },
  ],
  weapons: [],
  consumables: [],
}
