module.exports.story = {
  global: {
    description: "",
    name: "",
    category: "",
    public: "",
  },
  scenes: [
    {
      textbox: {
        "585ef7d9-5173-458a-a994-154aa92fac5c": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 104.99,
            top: 57.95,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "585ef7d9-5173-458a-a994-154aa92fac5c",
          link: "1",
          pos: {
            percX: 10.183317167798252,
            percY: 9.992456083629701,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "585ef7d9-5173-458a-a994-154aa92fac5c": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 104.99,
            top: 57.95,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "585ef7d9-5173-458a-a994-154aa92fac5c",
          link: "2",
          pos: {
            percX: 10.183317167798252,
            percY: 9.992456083629701,
          },
        },
      },
      background: null,
    },
    {
      textbox: {
        "585ef7d9-5173-458a-a994-154aa92fac5c": {
          obj: {
            type: "textbox",
            version: "5.3.0",
            originX: "left",
            originY: "top",
            left: 104.99,
            top: 57.95,
            width: 200,
            height: 45.2,
            fill: "black",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
            fontFamily: "Times New Roman",
            fontWeight: "normal",
            fontSize: 40,
            text: "Texte",
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: "left",
            fontStyle: "normal",
            lineHeight: 1.16,
            textBackgroundColor: "",
            charSpacing: 0,
            styles: [],
            direction: "ltr",
            path: null,
            pathStartOffset: 0,
            pathSide: "left",
            pathAlign: "baseline",
            minWidth: 20,
            splitByGrapheme: false,
          },
          Actions: [],
          id: "585ef7d9-5173-458a-a994-154aa92fac5c",
          link: "0",
          pos: {
            percX: 10.182875947471258,
            percY: 9.992301180406859,
          },
        },
      },
      background: null,
    },
  ],
  heroes: [],
  weapons: [],
  consumables: [],
}
