module.exports.story = {
  global: {
    description: "",
    name: "",
    category: "",
    public: "",
  },
  scenes: [
    {
      textbox: {
        "fa8c25d7-3f52-44a8-b5d2-6ed5497ab234": {
          type: "textbox",
          version: "5.3.0",
          originX: "left",
          originY: "top",
          left: 0,
          top: 0,
          width: 200,
          height: 45.2,
          fill: "black",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Times New Roman",
          fontWeight: "normal",
          fontSize: 40,
          text: "Texte",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "left",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          id: "fa8c25d7-3f52-44a8-b5d2-6ed5497ab234",
          Actions: [],
        },
      },
    },
    {
      textbox: {},
      image: {},
      rect: {},
    },
    {
      textbox: {},
      image: {},
      rect: {},
    },
    {
      textbox: {},
      image: {},
      rect: {},
    },
    {
      textbox: {},
      image: {},
      rect: {},
    },
    {
      textbox: {},
      image: {},
      rect: {},
    },
    {
      textbox: {},
      image: {},
      rect: {},
    },
  ],
}
